- src/api/models.py
> Modelado de base de datos

- src/api/admin.py
- src/api/routes.py
> backend quotation post

- package-lock.json
- package.json
- src/api/models.py
- src/api/routes.py
- src/front/js/component/QuotationInputs.js
- src/front/js/component/background.js
- src/front/js/config.js
- src/front/js/layout.js
- src/front/js/pages/CreateQuotation.js
- src/front/js/pages/home.js
- src/front/js/store/flux.js
- src/front/styles/background.css
- src/front/styles/createQuotation.css
- src/front/styles/quotationInputs.css
- template.html
Funcionalidad crear cotización lista!! <3
> Frontend create quotation

- src/app.py
> add login route

- src/front/js/layout.js
> change route layout

- src/front/js/layout.js
> Login front end

- src/front/js/pages/Register.js
add view register and make changes to flux file
> register front

- src/front/js/layout.js
- src/front/js/store/flux.js
> Register front end

- src/app.py
add route of register in app.py file
> route register

- package-lock.json
- src/api/models.py
- src/api/routes.py
- src/front/js/layout.js
> Correccion

- src/api/models.py
> add row db user

- Pipfile
- Pipfile.lock
- src/app.py
- src/front/js/layout.js
- src/front/js/pages/ResetPasswordRequest.js
- src/front/js/store/flux.js
add password request back and front end
> password reset front and back

- src/app.py
- src/front/js/layout.js
- src/front/js/pages/ResetPasswordToken.js
- src/front/js/store/flux.js
add passwordUpdate, modified flux, app.py, and add Reset password token view
> add update password front/backEnd

- src/front/js/component/QuotationCard.js
- src/front/js/component/QuotationInputs.js
- src/front/js/component/background.js
- src/front/js/index.js
- src/front/js/pages/CreateQuotation.js
- src/front/js/pages/ListQuotations.js
- src/front/js/pages/Login.js
- src/front/js/pages/home.js
- src/front/js/store/appContext.js
> Ajustes en rutas e imports

- src/app.py
- src/front/js/layout.js
- src/front/js/pages/Login.js
- src/front/js/pages/Register.js
- src/front/js/pages/listProject.js
- src/front/js/store/flux.js
- src/front/styles/login.css
add id btn and form control and change class for className in register file
> change id btn

- src/front/js/pages/ListQuotations.js
- src/front/js/pages/clientList.js
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
Corrección vistas listar clientes, cotizaciones y correccion llaves en el flux
> Corrección de errores frontend

- src/front/js/layout.js
- src/front/js/pages/home.js
- src/front/styles/clientList.css
Se comentaron vistas que tenían estilos que influían en otras vistas y se agregó el login como inicio en la app
> Coreeccion de estilos app

- src/front/styles/listQuotation.css
Estilos CSS agregados a la lista de cotizaciones
> Estilos CSS agregados a las listas

- src/app.py
- src/front/js/layout.js
- src/front/js/pages/CreateQuotation.js
- src/front/js/pages/Profile.js
- src/front/js/store/flux.js
- src/front/styles/profile.css
add profile view. add code in flux and app.py
> add profile view

- src/front/js/component/footer.js
- src/front/js/component/navbar.js
- src/front/js/layout.js
- src/front/js/pages/Nosotros.js
- src/front/js/pages/home.js
- src/front/styles/home.css
- src/front/styles/navbar.css
- src/front/styles/nosotros.css
add nosotros view, modified home, add navbar css, add routes in layout
> add landing page

- src/front/js/component/background.js
- src/front/js/component/navbar.js
- src/front/js/pages/Login.js
- src/front/js/pages/Register.js
- src/front/styles/login.css
- src/front/styles/navbar.css
- src/front/styles/profile.css
- src/front/styles/register.css
add some css and add route profile in background component
> modified css and add rout profile in background

- src/front/js/pages/Login.js
> fix login view

- src/front/js/component/background.js
- src/front/js/store/flux.js
add logout in flux and add the action in the background
> add logout

- src/api/models.py
- src/app.py
- src/front/js/pages/Login.js
- src/front/js/pages/Register.js
- src/front/js/pages/ResetPasswordRequest.js
- src/front/js/pages/ResetPasswordToken.js
- src/front/js/pages/home.js
- src/front/js/store/flux.js
- src/front/styles/home.css
- src/front/styles/login.css
- src/front/styles/nosotros.css
- src/front/styles/register.css
- src/front/styles/resetPassword.css
- src/front/styles/updatePassword.css
add css reset password and modified foute in email sent
> add css request password

- src/api/models.py
- src/api/routes.py
- src/front/js/layout.js
- src/front/js/pages/addClient.js
- src/front/js/pages/clientInfo.js
- src/front/js/pages/editInfo.js
- src/front/js/store/flux.js
- src/front/styles/addClient.css
- src/front/styles/background.css
- src/front/styles/clientInfo.css
- src/front/styles/clientList.css
- src/front/styles/editInfo.css
> Ed ad info clientes

- src/front/js/layout.js
- src/front/js/pages/Login.js
- src/front/js/pages/Nosotros.js
- src/front/js/pages/Profile.js
- src/front/js/pages/Register.js
- src/front/js/pages/ResetPasswordRequest.js
- src/front/js/pages/ResetPasswordToken.js
- src/front/js/pages/home.js
- src/front/js/store/flux.js
- src/front/styles/resetPassword.css
- src/front/styles/updatePassword.css
add changes in request password views, and css for both, add alerts
> add css changes and add some alerts
